### ISSUE TITLE
Impossible d’installez le plugin

### ISSUE THREAD

**Issue by Libar19** [marn06/homebridge-vw#1]
Bonjour. J’ai une erreur lors de l’installation. Impossible d’installer le Plugin. 
merci pour ce projet !! 

![906ED2B7-0945-4548-A91C-C9BB89E6878A](https://user-images.githubusercontent.com/116975798/219820026-4a4a1acd-591a-4240-9848-4daeaf4b3839.jpeg)
![0952DDB0-33F1-42FF-ADA2-369E32764DCE](https://user-images.githubusercontent.com/116975798/219820032-cfcb9caf-8e4c-4c0d-938b-a66e3125ae79.jpeg)

**Comment by Libar19** [comment]
Ok the plugin work's !! The error was: i don't agree xcode on my mac.

**Comment by marn06** [comment]
Great to hear that.
