### ISSUE TITLE
install fails

### ISSUE THREAD

**Issue by r2shyyou** [marn06/homebridge-vw#1]
npm ERR! code 1
npm ERR! path /opt/homebridge/lib/node_modules/homebridge-vw
npm ERR! command failed
npm ERR! command sh -c -- sh ./install.sh
npm ERR! > homebridge-vw@0.0.66-alpha python
npm ERR! > python3 -m venv dist/venv && dist/venv/bin/pip3 install beautifulsoup4 jsonpickle requests xmltodict
npm ERR! 
npm ERR! The virtual environment was not created successfully because ensurepip is not
npm ERR! available.  On Debian/Ubuntu systems, you need to install the python3-venv
npm ERR! package using the following command.
npm ERR! 
npm ERR!     apt-get install python3-venv
npm ERR! 
npm ERR! You may need to use sudo with that command.  After installing the python3-venv
npm ERR! package, recreate your virtual environment.
npm ERR! 
npm ERR! Failing command: ['/opt/homebridge/lib/node_modules/homebridge-vw/dist/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2023-01-27T20_19_06_410Z-debug-0.log

**Comment by marn06** [comment]
Hi 
Have you tried running apt-get install python3-venv? And which version of Python3 is configured on your system? Run Python3 —version.
This plug-in is still in an alpha state and is currently not that functional, I am still working on it.

**Comment by r2shyyou** [comment]
have not tried running apt-get install python3-venv and understand it's still in alpha. no problem. will try and will let you know if i run into other issues. thanks for the quick response!
