### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Libar19** [marn06/homebridge-vw#2]
can you add a switch for battery charging for hybrids? I tried to modify your plug-in, but I don't have the required knowledge. if not, it is in progress. On my side, I managed to add the switch on HomeKit and the python commands, but I must have some errors because it does not work

**Comment by marn06** [comment]
Hi Libar19
Sure that can also be implemented, but I don't have time for it currently and I would like to focus on the existing features which are still not working 100%. When starting climatisation the car is requested to start both window heating and climatisation and sometimes it fails. Another issue I experienced was that I needed to accept new terms and conditions which also did not work automatically due to the page used is an SPA making the implemented webscraper fail.
Let me know which errors you have and I might be able to assist.

**Comment by r2shyyou** [comment]
@marn06 for my part, it seems that i was able to unlock the car but can't lock it 😱

**Comment by marn06** [comment]
Hi @r2shyyou 
Please take a look at the homebridge log, this is how it should look when locking:
[3/2/2023, 11:04:06 AM] [VW Passat] Set locked state 1
[3/2/2023, 11:04:07 AM] [VW Passat] Python: [02/03/2023 11:04:07] [WeConnect::INFO] Doors status: {"lock_left_front": "closed", "open_left_front": "closed", "lock_left_rear": "closed", "open_left_rear": "closed", "lock_right_front": "closed", "open_right_front": "closed", "lock_right_rear": "closed", "open_right_rear": "closed", "lock_trunk": "closed", "open_trunk": "closed", "lock_hood": "closed", "open_hood": "closed"}
[3/2/2023, 11:04:08 AM] [VW Passat] Python: [02/03/2023 11:04:08] [WeConnect::INFO] {'rluActionResponse': {'requestId': 919450606, 'vin': 'XXXX'}}
[3/2/2023, 11:04:19 AM] [VW Passat] Python: [02/03/2023 11:04:19] [WeConnect::INFO] Doors status: {"lock_left_front": "locked", "open_left_front": "closed", "lock_left_rear": "locked", "open_left_rear": "closed", "lock_right_front": "locked", "open_right_front": "closed", "lock_right_rear": "locked", "open_right_rear": "closed", "lock_trunk": "locked", "open_trunk": "closed", "lock_hood": "closed", "open_hood": "closed"}
State after 10 seconds: true

**Comment by r2shyyou** [comment]
this is what i get when trying to lock:

> [02/03/2023, 12:14:15] [VW ID.4] Python: [02/03/2023 12:14:15] [API::WARNING] X-client-id not found. Requesting a new one
> 
> [02/03/2023, 12:14:15] [VW ID.4] Python: [02/03/2023 12:14:15] [API::CRITICAL] Raising error msg: Error 400:
> 
> [02/03/2023, 12:14:15] [VW ID.4] Python: [02/03/2023 12:14:15] [WeConnect::ERROR] VWError: Error 400:
> 
> [02/03/2023, 12:14:15] [VW ID.4] Set locked state Error: [02/03/2023 12:14:15] [WeConnect::ERROR] VWError: Error 400:
> 
> [02/03/2023, 12:14:15] [VW ID.4] Revert to: UNSECURED
> [02/03/2023, 12:14:17] [VW ID.4] Get locked state
> [02/03/2023, 12:14:17] [VW ID.4] Multiple requests within 60 seconds, ignored
> [02/03/2023, 12:14:17] [VW ID.4] Get climatisation state
> [02/03/2023, 12:14:17] [VW ID.4] Multiple requests within 60 seconds, ignored

**Comment by marn06** [comment]
Can you navigate to NativeAPI.py and change:
logger.setLevel(logging.getLogger().level)
to
logger.setLevel('DEBUG')

And then send the log after restarting homebridge?

**Comment by r2shyyou** [comment]
see attached
[homebridge.log.txt](https://github.com/marn06/homebridge-vw/files/10871532/homebridge.log.txt)

**Comment by marn06** [comment]
Hi @r2shyyou 
I just deleted the comment because it contains rather sensitive data. Can you check that spin you entered is correct ? the 4 digit code.

**Comment by r2shyyou** [comment]
@marn06 

Spin is correct

**Comment by marn06** [comment]
@Libar19 I have added battery service but it doesn't show as separate accessory in homekit.

**Comment by marn06** [comment]
@r2shyyou do you continue to get [02/03/2023 13:46:53] [API::WARNING] Access file not found ? Because the python program should create an access and session file and if it doesn't it might be permission issues.. But first of all, please make sure you are running the latest version.

**Comment by Libar19** [comment]
> @Libar19 I have added battery service but it doesn't show as separate accessory in homekit.

Thank's. I have bettery level in homebridge. I try to add the charge switch in homebridge

**Comment by r2shyyou** [comment]
> @r2shyyou do you continue to get [02/03/2023 13:46:53] [API::WARNING] Access file not found ? Because the python program should create an access and session file and if it doesn't it might be permission issues.. But first of all, please make sure you are running the latest version.

@marn06 yes, i do continue to get that error after updating to the latest version

**Comment by marn06** [comment]
@r2shyyou please try again in the new version 0.0.98-alpha, where I have added the response text when response is not valid json.

@Libar19  I have added a switch for charging.

**Comment by r2shyyou** [comment]
> @r2shyyou please try again in the new version 0.0.98-alpha, where I have added the response text when response is not valid json.
> 
@marn06 thanks, i tried and the result is the same as before

**Comment by marn06** [comment]
@r2shyyou can you post the response after the malformed JSON error?

**Comment by r2shyyou** [comment]
> @r2shyyou can you post the response after the malformed JSON error?

@marn06 sorry, not sure what this means. malformed JSON error?

**Comment by marn06** [comment]
@r2shyyou you should get an error like this in the log:
[02/03/2023 13:46:55] [API::DEBUG] Response error in JSON format

And after that error the actual message received should appear.

**Comment by r2shyyou** [comment]
> @r2shyyou you should get an error like this in the log: [02/03/2023 13:46:55] [API::DEBUG] Response error in JSON format
> 
> And after that error the actual message received should appear.

@marn06 i see, thanks. i just see the following:

> [03/03/2023 16:47:42] [API::DEBUG] Response error in JSON format
> [03/03/2023 16:47:42] [API::CRITICAL] Raising error msg: Error 400:
> [03/03/2023 16:47:42] [WeConnect::ERROR] VWError: Error 400:

**Comment by r2shyyou** [comment]
> > @r2shyyou you should get an error like this in the log: [02/03/2023 13:46:55] [API::DEBUG] Response error in JSON format
> 
> > 
> 
> > And after that error the actual message received should appear.
> 
> 
> 
> @marn06 i see, thanks. i just see the following:
> 
> 
> 
> > [03/03/2023 16:47:42] [API::DEBUG] Response error in JSON format
> 
> > [03/03/2023 16:47:42] [API::CRITICAL] Raising error msg: Error 400:
> 
> > [03/03/2023 16:47:42] [WeConnect::ERROR] VWError: Error 400:

@marn06 actually, there's more now. how best to communicate it to you? attach log file like before, and you delete it?

**Comment by Libar19** [comment]
Thank you @marn06 , on my side everything works !!. if I may, I deleted the window defroster from the main.py file. I think it makes more sense to have "air conditioning" and "defrost" with 2 different switches.



thank you again for your work.

**Comment by r2shyyou** [comment]
> Thank you @marn06 , on my side everything works !!. if I may, I deleted the window defroster from the main.py file. I think it makes more sense to have "air conditioning" and "defrost" with 2 different switches.
> 
> Do you think it is possible to have the car's charge level on Homekit?? or make homekit believe that the "charging" switch is battery-powered and display the car battery in the switch settings?
> 
> thank you again for your work.

@Libar19 everything works for you?? where are you located, generally speaking? US? I'm in Europe, which may or may not explain the differences we're experiencing

**Comment by Libar19** [comment]
I'm in france ^^

**Comment by r2shyyou** [comment]
> I'm in france ^^

me too!

**Comment by Libar19** [comment]
> > I'm in france ^^
> 
> 
> 
> me too!

Go private (telegram, @Libar19270)

**Comment by r2shyyou** [comment]
@marn06 thanks to @Libar19 it seems my issue might be that i have an ID.x and thus have a WeConnectID account and not simply WeConnect!

**Comment by marn06** [comment]
@r2shyyou my bad, I actually should have known this. Great that you figured it out, and I have now changed the example to a VW Passat instead, to make it less misleading :).

**Comment by marn06** [comment]
> > **Thank you @marn06 , on my side everything works !!. if I may, I deleted the window defroster from the main.py file. I think it makes more sense to have "air conditioning" and "defrost" with 2 different switches.**
Yes this is something that should be configurable with the config (later development) if you want it combined or not, but the combined solution was my personal preference :).
> > **Do you think it is possible to have the car's charge level on Homekit?? or make homekit believe that the "charging" switch is battery-powered and display the car battery in the switch settings?**
> > **thank you again for your work.**
You can already now see the battery % on the switch, but I think a humidity sensor would be good to display the battery %, I might look at that later.
